### ISSUE TITLE
Is it possible to execute the same http send action multiple times?

### ISSUE THREAD

**Issue by GiritharanR** [christophd/citrus#102]
I have a use case like to update the status of the server multiple times with the http call. This will be invoked in a time interval of every 30 seconds.

I have mocked this response with the help of citrus http server, but it produces the response only once.

Below are the actions i have used to mock the PUT operation of HTTP which i have mocked,

```
http().server(httpServer)
    .put("url")
	.messageType(MessageType.PLAINTEXT)
	.header("Content-Type=application/x-www-form-urlencoded")
	.payload("");
	
http().server(httpServer)
	.respond(httpStatus)
	.header("Content-Type", "application/json")
	.payload(response);
```

Can anyone suggest me how to respond with the same response multiple times without duplicating the action?

**Comment by christophd** [comment]
Have a look at the timer action container: http://www.citrusframework.org/reference/html/index.html#containers-timer

**Comment by GiritharanR** [comment]
thanks @christophd . It works fine
