### ISSUE TITLE
Before test methods in Java DSL

### ISSUE THREAD

**Issue by everflux** [christophd/citrus#109]
I have a test case extending JUnit4CitrusTestRunner. The example for ```waitFor()``` does only work with designer even though the caption states "Java DSL designer and runner".

When using a designer with the given example in a @Before method, a NPE is raised, is that expected? Could you provide an example ```waitFor().http()``` with the runner API?

**Comment by christophd** [comment]
The NPE in **@Before** is a known issue as Citrus Java DSL can not be used in before annotated methods at the moment. Did you also use the runner DSL methods in a **@Before** block? If not so could you please describe the issue with `waitFor().http()` in runner DSL?
