### ISSUE TITLE
Before/after suite methods in java DSL

### ISSUE THREAD

**Issue by GiritharanR** [christophd/citrus#110]
I am keen to know if there is an option to execute **citrus beforesuite** task (preferably an annotation) using **TestNGCitrusTestDesigner**.

In short, i want the below equivalent in java
```
<citrus:before-suite id="actionsBeforeSuite">
    <citrus:actions>
        <!-- list of actions before suite -->
    </citrus:actions>
</citrus:before-suite>
```

Early response is much appreciated.

**Comment by GiritharanR** [comment]
@christophd - Is it possible to achieve this feature in citrus?

**Comment by christophd** [comment]
The feature to execute before/after suite methods with Citrus Java DSL is missing and will be added with next version

**Comment by nimskhan** [comment]
@christophd Is this fixed in citrus version 2.7.2 ?
I can't find any reference in here: https://www.citrusframework.org/reference/html/

**Comment by christophd** [comment]
Have a look at this chapter: http://www.citrusframework.org/reference/html/#before-suite You will find description of TestDesignerBeforeSuiteSupport that you can extend from.

**Comment by nimskhan** [comment]
Okay, thanks.

**Comment by nimskhan** [comment]
Hello,
I need to do runner based send and get http calls in beforesuite which extends JUnit4CitrusTestRunner. How do I achieve this ?

For example in before suite: 
1. One POST call will generate the authentication token
2. GET call will get the token followed by the token extraction java based logic
3. The extracted/parsed token will be set to Global Variable which should accessible to all test cases

How do I achieve this in before suite?
