### ISSUE TITLE
Regex pattern support in citrus

### ISSUE THREAD

**Issue by GiritharanR** [christophd/citrus#111]
In citrus we are unable to mock the response with regex pattern.

For ex, if i want to mock a response for many request with dynamic paths, 

```
http().server("httpServer")
	.post("/path/234234345")
    .messageType(MessageType.JSON)
	.header("Content-Type", "application/json;charset=UTF-8"),
```

In the above, the numbers after path is dynamic. i want to mock with regex pattern for the same as below,

```
http().server("httpServer")
	.post("/path/.*")
    .messageType(MessageType.JSON)
	.header("Content-Type", "application/json;charset=UTF-8"),
```

Is it possible in citrus?

**Comment by christophd** [comment]
You can use validation matchers here:

    http().server("httpServer")
        .post("@matches('/path/.*')@")
        .messageType(MessageType.JSON)
        .header("Content-Type", "application/json;charset=UTF-8")

The validation matcher will check the regexp as you wish. By the way Citrus is able to mock incoming requests regardless of request paths. The path argument in the post() method is optional and just for validation purpose.

Let me know if this is working for you
