### ISSUE TITLE
evaluate(TestContext) method in HamcrestConditionExpression class is never executed

### ISSUE THREAD

**Issue by puneetkh** [christophd/citrus#123]
evaluate(TestContext) method in HamcrestConditionExpression class has more utility as it goes beyond simple interation based on index, instead String and Object related comparisons are also possible.

However, evaluate(TestContext) method in HamcrestConditionExpression class is never executed, This is happening because HamcrestConditionExpression class is always called using IteratingConditionExpression interface. However, the code for String and Object related comparisons resides in ConditionExpression interface implementation.

**Comment by christophd** [comment]
The evaluate(TestContext) method is executed by conditional container when evaluating if nested test actions should be executed or not. This is different to iterating conditions which do always refer to some iterating index by nature.
