### ISSUE TITLE
ConcurrentModificationException after last step using TestNGCitrusTestDesigner

### ISSUE THREAD

**Issue by DavidKorrigan** [christophd/citrus#136]
Hello,

We are using Citrus 2.6 and developed TestNGCitrusTestDesigner test cases.
On one test case we have a weird behavior on the last step, see under:

> 2016-09-28 10:41:51 DEBUG Citrus:198 - TEST STEP 5/5: In this test we receive the message
> 2016-09-28 10:41:51 DEBUG Citrus:220 - TEST STEP 5/7 SUCCESS

It says "TEST STEP 5/5" and then "TEST STEP 5/7", there is not more steps.

Just after, we get:
> 2016-09-28 10:41:51 ERROR Citrus:89 - TEST FAILED TC_RECEIVE_MSG_Test <com.soprasteria.citrus.test.it.cs.pubsub> Nested exception is: 
java.util.ConcurrentModificationException

You will find in attachment the full stacktrace

[ConcurrentModificationException_stacktrace.txt](https://github.com/christophd/citrus/files/497562/ConcurrentModificationException_stacktrace.txt)

Thx for your support.

**Comment by christophd** [comment]
I think you are using some Citrus Java DSL methods inside of a AbstractTestAction that is added to the test. You are not allowed to use the Java DSL inside of test action execute methods.

**Comment by DavidKorrigan** [comment]
Thx for your answer.
Indeed, it is exactly the mistake I did.
