### ISSUE TITLE
creating multiple consumer group in kafka cluster

### ISSUE THREAD

**Issue by sha198989** [christophd/citrus#157]
i am trying to create three different consumer groups for three topics. first how to create differnet consumer and then associated them with topics..

**Comment by christophd** [comment]
How do you connect with Kafka? As you might know Citrus has no direct Apache Kafka support yet. You can use the Apache Camel Kafka integration in Citrus though. Please describe what you are doing and what you have configured so far.

**Comment by sha198989** [comment]
Thanks for prompt response..
I am connecting with Kafka from logstash's input and output plugins of Kafka. I was trying to create multiple consumer groups in Kafka.. that I crated with --connect config/path to consumer properties. And I successfully created multiple consumer groups. But I have different doubt here.. when we create topic and with --partition parameter we provide partion for the topic ... will it not override the nun.partition parameter in server.properties configuration file????
Please reply .. I know I am asking something which is not relevant to this topic..

**Comment by christophd** [comment]
I would really love to help, but I have no idea how I can help you. I do not understand what the issue exactly is about. Maybe I lack of Apache Kafka knowledge here. Please give more information otherwise I am afraid I can not help you.

**Comment by sha198989** [comment]
Ok.. no worries .. thanks..
