### ISSUE TITLE
Citrus 2.6.2 issue with Spring 4.3.x for Camel in Action book

### ISSUE THREAD

**Issue by davsclaus** [christophd/citrus#161]
Hi

I just upgraded to 2.6.2 and we have a TODO in the pom.xml about an issue with spring 4.3.x. I tried to run the test and it still fails with latest spring version.

I wonder if you guys could help and take a look?
https://github.com/camelinaction/camelinaction2/commit/a91926c18acb85ebca1cb038e5d882569c1a4954#diff-e47bb94fc43b39788639fad581271e8dR17

**Comment by christophd** [comment]
Yes, that 2.6.2 Citrus version is still bound to Spring 4.2.x because Spring 4.3.x changed some behavior regarding handling of autowired list of beans. Citrus 2.7 which is likely to be released in December 2016 is then using Spring 4.3.x and Java 8.
