### ISSUE TITLE
LoggingClientInterceptor gets disabled when some interceptor is set

### ISSUE THREAD

**Issue by ahoeing** [christophd/citrus#180]
When adding some interceptor to the interceptor chain, the logging client interceptor gets removed. This seems to be some arbritary behavior that confused me. 

See class: com.consol.citrus.ws.client.WebServiceClient line 83 ff
```
        if (CollectionUtils.isEmpty(getEndpointConfiguration().getInterceptors()) && getEndpointConfiguration().getInterceptor() == null) {
            LoggingClientInterceptor loggingClientInterceptor = new LoggingClientInterceptor();
            loggingClientInterceptor.setMessageListener(context.getMessageListeners());

            getEndpointConfiguration().setInterceptor(loggingClientInterceptor);
        }
```

**Comment by christophd** [comment]
That is how it is supposed to work, when adding custom interceptors you may also decide where in the interceptor chain the logging should take place. This is why the default interceptor is not added automatically.

Maybe I should explain that thought in reference guide.

**Comment by karnis** [comment]
@christophd This behavior does not seem to be consistent to me when compared to the other Producers which never seem to lose the MessageListener notification.

An option would be 
* to append the interceptor to the end/beginning of the chain if its not present
* to optionally control the messageListener notification (on/off) in the endpoint configuration

Makes sense?
