### ISSUE TITLE
Unable to pass JSON response Paramaribo one test method send() to another send()  method

### ISSUE THREAD

**Issue by rkamiset** [christophd/citrus#181]
Dear team,
First of all, thank you so much for the beautiful framework that's undoubtedly delighting us in terms of easing test automation efforts.
Problem statement:
We have a need to retrieve response param, then process it (URLEncode) before passing it as input param to the subsequent REST call but we are unable to pass it deposits of different ways of trying it out. It just returns null.
Please see below post for the complete detail:

http://stackoverflow.com/questions/41192658/parsing-json-response-using-citrus-framework-for-urlencode

**Comment by christophd** [comment]
The encode operation destroys the "${myVar}" expression before Citrus is able to parse and interpret the expression as part of the message payload. You need to execute the encode operation as a Citrus function. How to write this function is described here: http://citrusframework.org/docs/custom-functions/

You end up having something like:

    designer.send("CitrusContext")
        .messageType(MessageType.JSON)
        .message(new HttpMessage("custom:urlEncode('appStoreBundleId=com.testmerchant.sampleapp&version=APP%2BBUILD%2BVERSION&channelId=MPD&spid=**${myVar}**&type=json&chasePayMerchantId=1390xxx')").method(HttpMethod.POST));

**Comment by rkamiset** [comment]
Thank you Christoph for the help. It really helped to get past the error.

Sincerely,
Raj.
iPhone. iTypos.
