### ISSUE TITLE
CitrusTest does not fail if assertEquals fails

### ISSUE THREAD

**Issue by ahoeing** [christophd/citrus#183]
A simple test that should fail result in a success for Citrus.

```
public class TestTest extends JUnit4CitrusTestRunner {

  @Test
  @CitrusTest
  public void test() {
    assertEquals("a", "b");
  }

}
```

Result output
```
18:41:55,110 INFO         citrus.Citrus| 
18:41:55,111 INFO         citrus.Citrus|  TestTest.test .................................................. SUCCESS
18:41:55,111 INFO         citrus.Citrus| 
18:41:55,111 INFO         citrus.Citrus| TOTAL:	1
18:41:55,112 DEBUG        citrus.Citrus| SKIPPED:	0 (0.0%)
18:41:55,112 INFO         citrus.Citrus| FAILED:	0 (0.0%)
18:41:55,112 INFO         citrus.Citrus| SUCCESS:	1 (100.0%)
18:41:55,112 INFO         citrus.Citrus| 
18:41:55,112 INFO         citrus.Citrus|
```

**Comment by christophd** [comment]
Yes, this is misleading. However you are not using any Citrus test action here. So from Citrus point of view everything is ok. The JUnit test case should fail as expected with respective error reports though.

I will have a look how we can transmit the error to Citrus although the error is out of Citrus scope here.

**Comment by toschneck** [comment]
@christophd maybe you can use some kind of Interceptor here

**Comment by christophd** [comment]
Also see #287 which is related to this issue
