### ISSUE TITLE
Is it possible to add sql's called in test reports?

### ISSUE THREAD

**Issue by furknyavuz** [christophd/citrus#186]
Hi,

In our test report we want to see which sql's called. We investigated the source code, but seems like only you are logging to logger. Can we add called sql's to test report?

Thanks,

**Comment by christophd** [comment]
You would have to implement a custom [TestReporter](https://github.com/christophd/citrus/blob/master/modules/citrus-core/src/main/java/com/consol/citrus/report/TestReporter.java) that gets access to the executed test actions (sql actions) as [TestActionListener](https://github.com/christophd/citrus/blob/master/modules/citrus-core/src/main/java/com/consol/citrus/report/TestActionListener.java). Then you could create a custom report.
