### ISSUE TITLE
Unable to retrieve X-CSRF-TOKEN using Header

### ISSUE THREAD

**Issue by rkamiset** [christophd/citrus#187]
Citrus currently supports to retrieve the cookie info (httpOnly) using the standard header name "Set-Cookie" by default:
SMSESSION
auth-site-info
auth-user-info

X-CSRF-TOKEN is missing. Am I missing anything here? Is there any other header name, that I should use to fetch the authcsrftoken?

PS: It may sound similar to #184 but appreciate any workaround to fetch the csrftoken here. Thanks.

**Comment by christophd** [comment]
When client send Http header `X-CSRF-TOKEN` I am able to receive and validate this header on server side with:

    <http:header name="X-CSRF-TOKEN" value="${csrfToken}"/>

I do not see why this header should not be handled on Citrus Http server. Extract from header mechanism in receive action should also work. You can also add this header to the response header and client will get this header, too.
