### ISSUE TITLE
generateReports is called only from one Spring Context

### ISSUE THREAD

**Issue by ahoeing** [christophd/citrus#194]
Hi,

In my project, I have several test classes using different spring @ContextConfigurations.
I use the TestReporter interface for reporting.

For each Configuration, a new instance of the Test Reporter will be created but the generateTestsResults() gets only invoked once (I assume on the firtsly instantiated reporter).

**Comment by christophd** [comment]
The generateTestResults method is called after the test suite. So it is called only once at the very end of that whole test suite run.

**Comment by christophd** [comment]
You may want to use different test suite runs or test groups then to get separated test reports
