### ISSUE TITLE
Conditional validations possible

### ISSUE THREAD

**Issue by Ernesto-Maserati-CH** [christophd/citrus#199]
Is it possible to use conditional validations?

Like if in JSON at path A the value is B then expect that at path X that the value is Y?

**Comment by christophd** [comment]
You can use a Groovy script that has access to the json object structure for that as described at the end of this chapter http://www.citrusframework.org/reference/html/validation-json.html#json-message-validation

You could also use a combination of JsonPath and Hamcrest matchers like allOf() but I think the Groovy script is more comfortable
