### ISSUE TITLE
Maven Archetype for Citrus

### ISSUE THREAD

**Issue by AxelBaumann** [christophd/citrus#200]
The POM generated for a Citrus 2.7 project with the maven archetype from http://citrusframework.com sets the source and target version for Java to Java 7

`<properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <citrus.version>2.7</citrus.version>
  <slf4j.version>1.7.22</slf4j.version>
  <testng.version>6.10</testng.version>
  <activemq.version>5.14.3</activemq.version>
</properties>`

`<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.1</version>
  <configuration>
    <encoding>${project.build.sourceEncoding}</encoding>
    <source>1.7</source>
    <target>1.7</target>
  </configuration>
</plugin>`

Shouldn't it be **1.8** since Citrus 2.7 needs at least Java 8 ?

**Comment by christophd** [comment]
Sorry for that, thanks for pointing to it

**Comment by christophd** [comment]
Fixed with https://github.com/christophd/citrus-tools/commit/ba18172ce558fa451cb736302ae7da433267ff30
