### ISSUE TITLE
Unable to use Amazon ELB cookie, help needed

### ISSUE THREAD

**Issue by GregoryOrciuch** [christophd/citrus#202]
Hi,

Looks like, citrus (2.7) cant eat well the AWS's LoadBalancer cookie, which is generated by their load balancer.

11:43:08,971 DEBUG ol.RequestAddCookies| CookieSpec selected: default
11:43:09,504 DEBUG            http.wire| http-outgoing-0 << "Set-Cookie: AWSALB=svqs/HoNujyBawoGyMKKiTGNz+XyaDZcmd5qh+RK0J48c7IOMCh3i3qvorRKcXBrxW16PX+h4lkphlpSyi0s3BpBZiVY6/kZUXP1PPQDugC2zKcnySU3UKXk08o1; Expires=Thu, 16 Feb 2017 10:43:09 GMT; Path=/[\r][\n]"
11:43:09,504 DEBUG            http.wire| http-outgoing-0 << "Set-Cookie: BPC_JSESSIONID=eEu7Rhy32IZ_Q57Ri1MJW6BOYibEzD1r0vwX7f4z.8b970c2fa934; path=/; HttpOnly[\r][\n]"

end then

11:43:09,526 WARN  sponseProcessCookies| Invalid cookie header: "Set-Cookie: AWSALB=svqs/HoNujyBawoGyMKKiTGNz+XyaDZcmd5qh+RK0J48c7IOMCh3i3qvorRKcXBrxW16PX+h4lkphlpSyi0s3BpBZiVY6/kZUXP1PPQDugC2zKcnySU3UKXk08o1; Expires=Thu, 16 Feb 2017 10:43:09 GMT; Path=/". Invalid 'expires' attribute: Thu, 16 Feb 2017 10:43:09 GMT
11:43:09,527 DEBUG sponseProcessCookies| Cookie accepted [BPC_JSESSIONID="eEu7Rhy32IZ_Q57Ri1MJW6BOYibEzD1r0vwX7f4z.8b970c2fa934", version:0, domain:impl.dfd-aws.com, path:/, expiry:null]

Any idea how to set different CookieSpec, like a CookiePolicy.BROWSER_COMPATIBILITY or custom ?

**Comment by GregoryOrciuch** [comment]
ok, I've been pushed by time, so this is workaround

Make a class like this:

```
import org.apache.http.client.HttpClient;
import org.apache.http.client.params.ClientPNames;
import org.apache.http.client.params.CookiePolicy;
import org.apache.http.impl.client.DefaultHttpClient;
import org.springframework.beans.factory.FactoryBean;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.http.client.HttpComponentsClientHttpRequestFactory;

public class CookieSpecRequestFactory implements FactoryBean<HttpComponentsClientHttpRequestFactory>, InitializingBean {


	private HttpClient httpClient;

	@Override public HttpComponentsClientHttpRequestFactory getObject() throws Exception {

		httpClient.getParams().setParameter(ClientPNames.COOKIE_POLICY, CookiePolicy.BROWSER_COMPATIBILITY);
		return new HttpComponentsClientHttpRequestFactory(httpClient);
	}

	@Override public Class<?> getObjectType() {
		return HttpComponentsClientHttpRequestFactory.class;
	}

	@Override public boolean isSingleton() {
		return false;
	}

	@Override public void afterPropertiesSet() throws Exception {
		if (httpClient == null) {
			httpClient = new DefaultHttpClient();
		}

	}
}

```

Then  attach this custom factory to your citrus context:
```
<bean id="customFactory" class="com.foo.bar.CookieSpecRequestFactory"/>

  <citrus-http:client id="myHttpClient"
                      request-url="http://somethingOnaws.com"
                      content-type="application/json"
                      timeout="5000"
                      request-factory="customFactory"/>
```

voila!

**Comment by christophd** [comment]
That is exactly how I would have done it, great!

**Comment by christophd** [comment]
I would suggest this workaround to be the solution how it should be done, Ok with that?

**Comment by GregoryOrciuch** [comment]
Sure

**Comment by christophd** [comment]
Fine, then I close this issue
