### ISSUE TITLE
http().client().send().post()

### ISSUE THREAD

**Issue by gucce** [christophd/citrus#203]
The Java DSLs `send()` and `receive()` methods, e.g. in `HttpClientActionBuilder`, don't restrict the use case to send or receive respectively. As a matter of fact, they don't affect the use case at all:

```java
    public HttpClientActionBuilder send() {
        return this;
    }
```

This means, these methods could also be concatenated and would have no effect whatsoever. So this would be syntactically correct:

```java
http().client().send().receive().receive().send().post("/some/path")...
```

This is clearly a problem and should be addressed so that the aforementioned methods restrict the use cases appropriately.

This affects several classes:

- `HttpClientActionBuilder`
- `HttpClientActionBuilder`
- `SoapClientActionBuilder`
- `SoapServerActionBuilder`

**Comment by christophd** [comment]
Issue has already been fixed in 2.7 with https://github.com/christophd/citrus/commit/bb5c00d522fcd79ef0458c5c3192c46d3c7075ea
