### ISSUE TITLE
Help: Java 7

### ISSUE THREAD

**Issue by ahoeing** [christophd/citrus#207]
Hi,

is there a way to write test cases in Java 7 JDK, i.e. without lamda expressions (JRE would be JAVA 8).
I have an old version of eclipse and I am not able to update due to some organizational reasons.

André

**Comment by christophd** [comment]
You can only use Citrus up to 2.6.2 version with Java 7. Version 2.7 is compiled with Java 8 so running via Java 7 JDK is not possible.

When using Citrus 2.6.2 you can use nested builder instances instead of Java 8 lambda expressions:

    send(new BuilderSupport<SendMessageBuilder>() {
            @Override
            public void configure(SendMessageBuilder builder) {
                builder.endpoint(messageEndpoint)
                        .payload("Foo");
            }
        });

With Lambda the same would be:

    send(builder -> builder.endpoint(messageEndpoint)
                        .payload("Foo"));
