### ISSUE TITLE
How to run on command line Citrus Integration Tests? 

### ISSUE THREAD

**Issue by SherzodNurjonov** [christophd/citrus#208]
Hi @christophd ,
I couldn't run Citrus Integration Tests from command line. The result is following
`> mvn -Dslconf.file.base={some path to conf files} test`
`Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.470 s
[INFO] Finished at: 2017-02-16T20:10:54+02:00
[INFO] Final Memory: 20M/619M
[INFO] ------------------------------------------------------------------------`

BTW, I can run all ITs from Intellij Idea without any issue.

**Comment by christophd** [comment]
You may need to use `mvn integration-test` goal as Citrus tests are bound to Maven integration-test phase by default. `mvn test` executes the unit test phase only.
