### ISSUE TITLE
Designer vs Runner in cucumber module

### ISSUE THREAD

**Issue by mikeloll** [christophd/citrus#220]
In the cucumber module there are duplicate `@Given` annotated methods which have the same regex, but one uses a `TestDesigner` and the other a `TestRunner`.  These classes are located in the designer and runner packages.  What if the difference?

For reference, see `DockerSteps::setClient` in packages `com.consol.citrus.cucumber.step.runner.docker` and `com.consol.citrus.cucumber.step.designer.docker`.

runner: 
```java
    @Given("^docker client \"([^\"]+)\"$")
    public void setClient(String id) {
        if (!citrus.getApplicationContext().containsBean(id)) {
            throw new CitrusRuntimeException("Unable to find docker client for id: " + id);
        }

        dockerClient = citrus.getApplicationContext().getBean(id, DockerClient.class);
    }
```

designer:
```java
    @Given("^docker client \"([^\"]+)\"$")
    public void setClient(String id) {
        if (!citrus.getApplicationContext().containsBean(id)) {
            throw new CitrusRuntimeException("Unable to find docker client for id: " + id);
        }

        dockerClient = citrus.getApplicationContext().getBean(id, DockerClient.class);
    }
```

**Comment by christophd** [comment]
Test designer collects all Citrus Java fluent API method calls, constructs the whole test case and executes all actions as a whole at the end. Test runner executes the Java fluent API method calls right away step by step.

More of a historical difference how to execute test actions in Citrus. Read more about that in http://www.citrusframework.org/reference/html/test-case.html#java-dsl-test-designer and http://www.citrusframework.org/reference/html/test-case.html#java-dsl-test-runner.

When using Cucumber BDD steps I personally would prefer to use runner as you get immediate failure in step in contrast to having all steps getting performed and getting errors at the very end of the step execution.

**Comment by mikeloll** [comment]
I apologize, I totally missed that documentation.  I also see in the cucumber module docs where you show how to use the glue code to pick between the two.  Thank you!

As far as I am concerned, feel free to close this.  My issue has been answered.

**Comment by christophd** [comment]
Ok, no problem
