### ISSUE TITLE
Extending with new message types

### ISSUE THREAD

**Issue by mikeloll** [christophd/citrus#222]
Is it possible to extend citrus with new message types?  I don't think so from looking around the docs.  What I'm trying to do is define some higher level constructs for a message format called "foo" (for example).

At their core, foo message types are json.  But they follow a certain format, etc, that I'd like to standardize so boilerplate isn't present in the tests.  And it also provides value to me that I can have a message action that says `<message type="foo" />` instead of `<message type="json" />`.

One route is for me to define my own module, which I could do with some effort.  I'd define my own dsl or xml structure (e.g. `<foo .. />`).  But I'd like to piggyback on all of the underlying hard work already present in the core module.

Any ideas?

**Comment by christophd** [comment]
You can write custom message validator implementations that support your very special message type. Just set the message type to `'foo'` and write a custom message validator supporting this type. 

You just need to add the custom message validator to the message validator registry then as described in [customize-message-validators](http://www.citrusframework.org/reference/html/validation.html#customize-message-validators)

The custom message validator should extend https://github.com/christophd/citrus/blob/master/modules/citrus-core/src/main/java/com/consol/citrus/validation/DefaultMessageValidator.java and overwrite `supportsMessageType()`

**Comment by mikeloll** [comment]
The validator will be called in a response, right?  Can I also validate before it is sent in a request?

**Comment by christophd** [comment]
You could add a custom message construction interceptor (com.consol.citrus.validation.interceptor.MessageConstructionInterceptor) that is called with the constructed message before that is sent out. You can add this interceptor globally as Spring bean to the Citrus Spring application context. All send and receive actions should automatically use this interceptor while processing.

The custom interceptor can also use Spring autowire mechanism in order to inject the Citrus XML message validators for schema validation.

**Comment by christophd** [comment]
About to close that issue, Ok for you?

**Comment by mikeloll** [comment]
Sorry about that, yes.  These past couple of weeks have been busy and I never got back here to thank you.  Thanks for the info.  I'll be trying this out.

**Comment by jimcakalic** [comment]
Sorry to pile on to this issue but we're considering something similar. We have, at present, internal legacy mainframe services that exchange messages over MQ. The payload is [ugh!] a fixed width string defined by a COBOL copybook record. I want to be able to handle this as something more robust than plaintext. Basically be able to define message payloads (in Cucumber) with variable interpolation and response validation using the Hamcrest matchers. I think I understand how to write/register the MessageValidator -- doc looks pretty good on that. But I'm unclear on the MessageConstructionInterceptor. You say "add as a Spring bean to the Citrus Spring application context". Am I missing something or does Citrus use ApplicationContext.getBeansOfType to discover all known implementations of the interface? Also, is it possible using the named message feature in the Cucumber glue to specify the message type of the payload?

**Comment by christophd** [comment]
Citrus is using autowiring of Spring beans. So all implementations of message construction interceptors will be loaded to the framework by adding a new bean to the application context. Please open a new issue on that Cucumber question as it is misplaced in this issue. Thanks!
