### ISSUE TITLE
documentation clarity issue

### ISSUE THREAD

**Issue by ph-ms** [christophd/citrus#223]
Re citrus/src/site/_posts/2016-10-01-sample-http.md

1. It is not clear programmatically how the post() code snippet and the receive() code snippet related.

2. .response() is going to throw an assertion error if needed right?  (an implicit 'should be')

3. how about working in something like content(equalTo("something expected")) in the same example - chained after the 200 check.

**Comment by christophd** [comment]
Each receive() in Citrus is a 'should be' as you can give an expected message content. In that particular example the Http Status is expected to be '200 OK'. You can easily add payload validation to that response by adding payload("expected") or by adding XPath or JsonPath expressions that are evaluated.

**Comment by ph-ms** [comment]
Yeah, I'm sorry, but it's still not clear. I'm developer who mocks from JMock 1.0 onwards, and I can't quite follow what your saying (or the code posted) on the site.  How is the code fragment that features post() related to the code fragment that features receive() ?

**Comment by christophd** [comment]
There is an internal message correlation that is done with test local context. So the test case knows based on this context that a message has been sent with post() and that the receive operation is correlated to that. The correlation is done automatically.

The good thing is that you can do some additional stuff between post() and receive. Or the other way round you can receive a message do something else and send back a response later in the test. Correlation of messages is done automatically based on the test context.

**Comment by christophd** [comment]
By the way correlation across different endpoints and multiple messages on the same endpoint in one single test are also supported with the default correlation strategy. In addition to that correlation strategies within test context can be adjusted and customized. But these are more advanced topics that require deep insight and explanation on the implementation details.

Most of the time it is best to fit with the default auto correlation mechanism as it is very powerful

**Comment by christophd** [comment]
Will close that issue soon when you are Ok with that
