### ISSUE TITLE
Weblogic JMS integration via Citrus frame work

### ISSUE THREAD

**Issue by Vineet-happy** [christophd/citrus#225]
We are working on WebLogic JMS integration using Citrus frame work.
We are stuck in connection factory creation if anyone has worked in such implementation pls share sample code.
Current architecture what we are using is as provided below.

JavaSPring -> JMS(request Queue)

**Comment by christophd** [comment]
I guess you are having problems to add the WebLogic JMS connection factory to the Citrus Spring configuration, right? You can do this via JNDI lookup. Is that what you are looking for? Otherwise please give more information on the problem that you have.

**Comment by Vineet-happy** [comment]
Thanks for your help we tried following and still not working

Attaching all the files and logic implemented pls go through and suggest us the appropriate solution

content of "citrus-context.xml"

<?xml version="1.0" encoding="UTF-8"?>
 
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:citrus="http://www.citrusframework.org/schema/config"
       xmlns:citrus-ws="http://www.citrusframework.org/schema/ws/config"
       xmlns:citrus-http="http://www.citrusframework.org/schema/http/config"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:citrus-jms="http://www.citrusframework.org/schema/jms/config"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-2.5.xsd
       http://www.citrusframework.org/schema/jms/config http://www.citrusframework.org/schema/jms/config/citrus-jms-config.xsd
       http://www.citrusframework.org/schema/config http://www.citrusframework.org/schema/config/citrus-config-1.1.xsd">

  
   <citrus-jms:endpoint id="todoEndpoint"
                          destination-name="XYZ/jms/queue/GNBMRequest"
                          connection-factory="connectionFactory" />
  
  <bean id="qcf" class="org.springframework.jndi.JndiObjectFactoryBean">
        <property name="jndiEnvironment">
            <props>
                <prop key="java.naming.factory.initial">weblogic.jndi.WLInitialContextFactory</prop>
                <prop key="java.naming.provider.url">t3://localhost:7280</prop>
            </props>
            </property>
       <property name="jndiName" value ="weblogic.examples.jms.QueueConnectionFactory"/>
    </bean>   
    <bean id="jt" class="org.springframework.jms.core.JmsTemplate102">
    	<property name="connectionFactory" ref ="qcf"></property>
    	</bean>
    
  <bean id="queue" class="org.springframework.jndi.JndiObjectFactoryBean">
       <property name="jndiEnvironment">
            <props>
                <prop key="java.naming.factory.initial">weblogic.jndi.WLInitialContextFactory</prop>
                <prop key="java.naming.provider.url">t3://localhost:7280</prop>
            </props>
            </property>
        <property name="jndiName" value="XYZ/jms/queue/GNBMRequest"/>
        
    </bean>
    
      
    
       <bean id="connectionFactory" class="org.springframework.jndi.JndiObjectFactoryBean">
        <property name="jndiTemplate">
            <ref bean="jndiTemplate" />
        </property>
        <property name="jndiName">
            <value>XYZ/jms/ConnectionFactory</value>
        </property>
    </bean> 
    
     
    <bean id="jmsDestinationResolver" class="org.springframework.jms.support.destination.JndiDestinationResolver">
        <property name="jndiTemplate">
            <ref bean="jndiTemplate" />
        </property>
        <property name="cache">
            <value>true</value>
        </property>
    </bean>
 
   <bean id="sendGreeting" class="com.consol.citrus.jms.JmsMessageSender">
        <property name="destinationName" value="XYZ/jms/queue/GNBMRequest"/>
        <property name="connectionFactory">
            <ref bean="connectionFactory" />
        </property>   
        <property name="destinationResolver">
            <ref bean="jmsDestinationResolver" />
        </property>       
    </bean>
 
     <bean id="receiveGreeting" class="com.consol.citrus.jms.JmsMessageReceiver">
        <property name="destinationName" value="XYZ/jms/queue/GNBMAsyncResponse"/>
        <property name="connectionFactory">
            <ref bean="connectionFactory" />
        </property>       
        <property name="destinationResolver">
            <ref bean="jmsDestinationResolver" />
        </property>   
    </bean> 

   <citrus:jms-message-sender id="getOrdersRequestSender"
                               destination-name="XYZ/jms/queue/GNBMRequest"/> 
 
  <citrus:jms-message-receiver id="getOrdersResponseReceiver"
                                 destination-name="XYZ/jms/queue/GNBMAsyncResponse"/>



Java file

 */
public class TodoListIT extends TestNGCitrusTestDesigner {

    
    @Autowired
    private JmsEndpoint todoEndpoint;

    @Test
    @CitrusTest
    public void testAddTodoEntry() {
       // variable("hello");

    	 send(todoEndpoint)
         .payload("welcome ");
}
}
[context_xml.txt](https://github.com/christophd/citrus/files/847928/context_xml.txt)


_________

Once the above setting is done we have called the java class using .payload without using .header() pls clarify if the approach is correct

Eagerly waiting for positive reply

**Comment by Vineet-happy** [comment]
Thanks for your help we tried following and still not working

Attaching all the files and logic implemented pls go through and suggest us the appropriate solution

content of "citrus-context.xml"

<citrus-jms:endpoint id="todoEndpoint"
destination-name="XYZ/jms/queue/GNBMRequest"
connection-factory="connectionFactory" />

weblogic.jndi.WLInitialContextFactory t3://localhost:7280 weblogic.jndi.WLInitialContextFactory t3://localhost:7280
</bean>

  

   <bean id="connectionFactory" class="org.springframework.jndi.JndiObjectFactoryBean">
    <property name="jndiTemplate">
        <ref bean="jndiTemplate" />
    </property>
    <property name="jndiName">
        <value>XYZ/jms/ConnectionFactory</value>
    </property>
</bean> 

 
<bean id="jmsDestinationResolver" class="org.springframework.jms.support.destination.JndiDestinationResolver">
    <property name="jndiTemplate">
        <ref bean="jndiTemplate" />
    </property>
    <property name="cache">
        <value>true</value>
    </property>
</bean>
 <bean id="receiveGreeting" class="com.consol.citrus.jms.JmsMessageReceiver">
    <property name="destinationName" value="XYZ/jms/queue/GNBMAsyncResponse"/>
    <property name="connectionFactory">
        <ref bean="connectionFactory" />
    </property>       
    <property name="destinationResolver">
        <ref bean="jmsDestinationResolver" />
    </property>   
</bean> 
<citrus:jms-message-sender id="getOrdersRequestSender"
destination-name="XYZ/jms/queue/GNBMRequest"/>

<citrus:jms-message-receiver id="getOrdersResponseReceiver"
destination-name="XYZ/jms/queue/GNBMAsyncResponse"/>

Java file

*/
public class TodoListIT extends TestNGCitrusTestDesigner {

@Autowired
private JmsEndpoint todoEndpoint;

@Test
@CitrusTest
public void testAddTodoEntry() {
   // variable("hello");

	 send(todoEndpoint)
     .payload("welcome ");
}
}
context_xml.txt

Once the above setting is done we have called the java class using .payload without using .header() pls clarify if the approach is correct

Eagerly waiting for positive reply
[context_xml.txt](https://github.com/christophd/citrus/files/847955/context_xml.txt)

**Comment by christophd** [comment]
I am always using `jndi.properties` placed in the project in `src/test/resources` folder:

    java.naming.provider.url=t3://localhost:7001
    java.naming.factory.initial=weblogic.jndi.WLInitialContextFactory

Then in `citrus-context.xml` add spring-jee namespace to beans root element:

    <beans [...] xmlns:jee="http://www.springframework.org/schema/jee" schemaLocation="[...]
    http://www.springframework.org/schema/jee http://www.springframework.org/schema/jee/spring-jee.xsd">

Then you can use the XML components of Spring JEE support:

    <bean id="connectionFactory" class="org.springframework.jms.connection.SingleConnectionFactory">
        <property name="targetConnectionFactory">
            <jee:jndi-lookup jndi-name="weblogic.examples.jms.QueueConnectionFactory"/>
        </property>
    </bean>

    <jee:jndi-lookup id="todoQueue" jndi-name="XYZ/jms/queue/GNBMRequest" />

    <citrus-jms:endpoint id="todoEndpoint"
                      destination="todoQueue"
                      connection-factory="connectionFactory" />

Should work for you.
