### ISSUE TITLE
Line breaks in SOAP requests

### ISSUE THREAD

**Issue by martin-fekete-vds** [christophd/citrus#227]
Hi,

we are using the XML DSL of Citrus 2.7 to send messages to a server via SOAP.

We noticed a problem when trying to send a SOAP request with values containing line breaks.

The LF (`&#10;`) character specifying a line break in XML gets translated to CR+LF (\r\n) characters and is sent out this way.
This in turn gets translated by the the target server (writen in C++) into CR+CR+LF (\r\r\n), producing invalid data (Windows environment).

We believe the SOAP message payload should contain only the LF character as line break.

Simplest code to reproduce this issue in Citrus XML DSL:

```
<send endpoint="IASSoapClient">
	<message>
		<payload>
			<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
				<SOAP-ENV:Header/>
				<SOAP-ENV:Body>
					<value xsi:type="xsd:string">first line&#10;second line</value>
				</SOAP-ENV:Body>
			</SOAP-ENV:Envelope>
		</payload>
	</message>
</send>
```

What's your take on this issue?

Regards,
Martin Fekete

**Comment by christophd** [comment]
Of what component type is `IASSoapClient`?  `citrus-ws:client` or `citrus-http:client`?

I guess this is related to parsing the XML as DOM and serializing it back to String content. Please try to put the value into a CDATA section:

    <value xsi:type="xsd:string"><![CDATA[first line&#10;second line]]></value>

Maybe this solves the issue. In addition to that you can try to configure the default line separator character for Java and/or for the XML serlializer [(customize-xml-parser-and-serializer)](http://www.citrusframework.org/reference/html/validation-xml.html#customize-xml-parser-and-serializer).

**Comment by christophd** [comment]
Any news here? About to close this issue ...
