### ISSUE TITLE
Ignore element order when validating XML messages

### ISSUE THREAD

**Issue by srdeleon** [christophd/citrus#232]
Is there a way to ignore elements order when validating XML messages in Citrus?

Let's say we have the following scenario:

Configured response in Citrus:

><root>
	<elements>
		<element>A</element>
		<element>B</element>
		<element>C</element>
	</elements>
</root>

Incoming response when testing:

><root>
	<elements>
		<element>B</element>
		<element>C</element>
		<element>A</element>
	</elements>
</root>

Test result will be something like:

>Validation failed: Node value not equal for element 'element', expected 'A' but was 'B'
>Validation failed: Node value not equal for element 'element', expected 'B' but was 'C'
>Validation failed: Node value not equal for element 'element', expected 'C' but was 'A'

Thanks in advance!

**Comment by christophd** [comment]
The XML validation is based on the Document Object Model (DOM tree) and not able to ignore the order of elements. But you could use Xpath expressions for that. So you ignore the section in DOM tree template validation like this:

    <elements>@ignore@</elements>

And then you add Xpath expression validation to the receive action like this:

    number:count(//elements/element) = 3.0
    boolean://elements/element[. = 'A'] = true
    boolean://elements/element[. = 'B'] = true
    boolean://elements/element[. = 'C'] = true

Now you make sure that the elements do exist in the message payload without having to know the exact order of the elements.

**Comment by srdeleon** [comment]
Thanks Christoph! Tried your suggestion and works.
