### ISSUE TITLE
How to Query ?WSDL from a WebService or HTTP Endpoint

### ISSUE THREAD

**Issue by karnis** [christophd/citrus#245]
I would like to query `?WSDL` from a WebService or HTTP endpoint.

Querying with `.send().get().queryParam("WSDL", null)` results in `?WSDL=null`, querying with `get(?WSDL)` results in `/?WSDL`

Any ideas?

**Comment by christophd** [comment]
Thanks, this is a bug, should be fixed

**Comment by reviol** [comment]
Hi!
Did you resolved this issue?
Now, when I start my SoapServer, it cannot give wsdl out.
