### ISSUE TITLE
custom web-driver is not working with citrus-selenium

### ISSUE THREAD

**Issue by AndreasWier** [christophd/citrus#260]
When I specify a custom web-driver with citrus-selenium 2.7.1:
```xml
<citrus-selenium:browser id="seleniumBrowser"
            type="custom"
            web-driver="marionetteDriver"
            start-page="${base.uri}/"/>
```
 and start my test, then I get the error:

CitrusRuntimeException: Unsupported local browser type: custom

I think, this is because in 
https://github.com/christophd/citrus/blob/master/modules/citrus-selenium/src/main/java/com/consol/citrus/selenium/endpoint/SeleniumBrowser.java#start()
method 

the WebDriver is overwridden by the code:
```java
            if (getEndpointConfiguration().getWebDriver() != null) {
                webDriver = getEndpointConfiguration().getWebDriver();
            } if (StringUtils.hasText(getEndpointConfiguration().getRemoteServerUrl())) {
                webDriver = createRemoteWebDriver(getEndpointConfiguration().getBrowserType(), getEndpointConfiguration().getRemoteServerUrl());
            } else {
                webDriver = createLocalWebDriver(getEndpointConfiguration().getBrowserType());
            }
```
I think in line 102 it should be an `else if`.

Does anyone agree with my guess?

**Comment by christophd** [comment]
Confirmed, thank you for pointing to it!
