### ISSUE TITLE
Is there a way to report on ExtentReport

### ISSUE THREAD

**Issue by Geekays** [christophd/citrus#281]
I have just started looking at citrus framework. Thanks for the great work.

We are also using Selenium for the web based testing and using Extent Reports for reporting. Is there a way to use Extent Report from Citrus as well?

**Comment by christophd** [comment]
Citrus provides several reporting and listener interfaces that get informed about test state such as success or failure. You can add custom implementations of these interfaces to the Spring application context. The custom reporting class may then create Extent reports via Java API.

The listener interfaces are located in [com.consol.citrus.report](https://github.com/christophd/citrus/tree/master/modules/citrus-core/src/main/java/com/consol/citrus/report) package: MessageListener, TestSuiteListener, TestListener, TestActionListener, TestReporter

You can have a look at the default [LoggingReporter](https://github.com/christophd/citrus/blob/master/modules/citrus-core/src/main/java/com/consol/citrus/report/LoggingReporter.java) as a sample implementation.

**Comment by christophd** [comment]
Added a sample project exactly doing this: https://github.com/christophd/citrus-samples/tree/master/sample-reporting
