### ISSUE TITLE
Methods inside TestListener Implemented Class Execute Twice

### ISSUE THREAD

**Issue by bidhuj** [christophd/citrus#285]
Hi,
While Executing i observed the methods inside TestListener execute twice.
	}

	@Override
	public void onTestFinish(TestCase test) {

			extent.endTest(ETest);
			extent.flush();	
			
	}

	@Override
	public void onTestSuccess(TestCase test) {
	 
		log.info("Pass ");
        		
	}

This is the Method Executed twice everytime

**Comment by christophd** [comment]
Investigated and can not reproduce that error. I also added a new sample for exactly that custom Extent reporting. See https://github.com/christophd/citrus-samples/tree/master/sample-reporting

Please review the sample and let me know how it works for you.

**Comment by bidhuj** [comment]
<img width="768" alt="samplereport" src="https://user-images.githubusercontent.com/30194206/30326794-4e5ac218-97e7-11e7-8d48-2ba321425102.png">
Hi Chris,
Thanks much for the Help. I have a Test Automation Team here and They Have UI Automation, Mobile Automation and API Testing (Which i am currently Working), Inorder to set the Standards we have used Extent Report Version 2, I have followed your Steps but However getting the repetitive Results, Attached the Result ScreenShot as well as the code i have used.

Test Case Script:
package com.consol.citrus.integration.Demo;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.ImportResource;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;
import org.springframework.http.client.ClientHttpRequestInterceptor;

import com.consol.citrus.TestCaseMetaInfo.Status;
import com.consol.citrus.annotations.CitrusTest;
import com.consol.citrus.dsl.testng.TestNGCitrusTestDesigner;
import com.consol.citrus.http.client.HttpClient;
import com.consol.citrus.message.MessageType;
import com.relevantcodes.extentreports.ExtentTest;



public class SuccessFullLogin extends TestNGCitrusTestDesigner {
	
	  @Autowired (required=true)
	  @Qualifier("todoClient1")
	  
	   
	  private HttpClient todoClient1;
	//  public static com.relevantcodes.extentreports.ExtentReports extent = ExtentManager.getInstance();
	//  public static ExtentTest test;
	    @Test
	    @CitrusTest

	    public void TestPost() {
	    	variable("Uname", "admin");
	    	variable("Pwd", "admin");
	    	

	        http()
	        
	            .client(todoClient1)            
	            .send()
	            .post("/rest/api/user/login")
	            .contentType("application/json")
	           // .payload("{ \"userName\": \"${uN}\", \"password\": \"${pwd}\"}");
                .payload("{ \"userName\": \"${Uname}\", \"password\": \"${Pwd}\"}");

	        http()
	            .client(todoClient1)
	            .receive()
	            .response(HttpStatus.OK)
	            .validate("$.statusCode", "200");
                 
	       
	    
	       
	    }	
	    

	}

Implemented Reporter:

package com.consol.citrus.integration.Demo;

import com.consol.citrus.TestCase;
import com.consol.citrus.TestCaseMetaInfo;
import com.consol.citrus.report.AbstractTestListener;
import com.consol.citrus.report.TestReporter;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class ExtentReporter extends AbstractTestListener implements TestReporter {

	  public static ExtentReports extent=ExtentManager.getInstance();
	  public static ExtentTest ET;

    @Override
    public void onTestSuccess(TestCase test) {

    	ET=extent.startTest(test.getName());
        ET.log(LogStatus.PASS, "Pass");
    }

    @Override
    public void onTestSkipped(TestCase test) {
       
    }

    @Override	
    public void onTestFailure(TestCase test, Throwable cause) {
    	ET=extent.startTest(test.getName());
    	ET.log(LogStatus.FAIL, "FAIL",cause.toString());
    }
    

    @Override
    public void generateTestResults() {
    	extent.flush();
      
    }
   

    @Override
    public void clearTestResults() {
    	extent.close();	
    }


    /**
     * Initialize reports.
     */
  
}

**Comment by christophd** [comment]
Please also share the complete Spring application context configuration. I need to see how you have added the custom reporter as Spring bean.

**Comment by bidhuj** [comment]
HI Chris,
Attached the Spring Application contetxt File.
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:citrus="http://www.citrusframework.org/schema/config"
       xmlns:citrus-http="http://www.citrusframework.org/schema/http/config"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.citrusframework.org/schema/config http://www.citrusframework.org/schema/config/citrus-config.xsd
       http://www.citrusframework.org/schema/http/config http://www.citrusframework.org/schema/http/config/citrus-http-config.xsd">
	
    
    <citrus:namespace-context>
      <citrus:namespace prefix="xh" uri="http://www.w3.org/1999/xhtml"/>
    </citrus:namespace-context>

      <bean class="com.consol.citrus.integration.Demo.ExtentReporter"/>
          
       <bean class="com.consol.citrus.report.MessageTracingTestListener"/>
     

    <citrus-http:client id="todoClient"
                  request-url="http://localhost:8080/selling-point-service"
                  request-method="GET"/>


    
</beans>

**Comment by bidhuj** [comment]
Issue Resolved
