### ISSUE TITLE
Reporting of test results 

### ISSUE THREAD

**Issue by martinmaher** [christophd/citrus#287]
Hi,
When executing Citrus tests that use the TestNGCitrusTestRunner and one of the tests fail, then Citrus reports that the test succeeded. 

This appears to happen when the test includes java code that is not nested within a citrus action and this code throws an exception.

To reproduce the problem:
`
    @CitrusTest
    public void testShoudFail() {
        if(1==1){
            throw new RuntimeException("Oops");
        }
    }
`

When executed the following is logged:
TEST SUCCESS DummyIT.testShoudFail()
...
CITRUS TEST RESULTS
DummyIT.testShoudFail ...... SUCCES
TOTAL:	1
FAILED:	0 (0.0%)
SUCCESS:	1 (100.0%)

We are using Citrus version 2.7.2

Best regards
Martin

**Comment by karnis** [comment]
is this the same as #183 but for TestNG
