### ISSUE TITLE
Getting com.consol.citrus.exceptions.ActionTimeoutException

### ISSUE THREAD

**Issue by kdborkar** [christophd/citrus#295]
Problem statement : 
com.consol.citrus.exceptions.ActionTimeoutException: Action timeout while receiving message from channel 'soapJaxwsServer.inbound'.

Exception came when timeout(600000ms) in mock server configuration is over, sometime it is working.
7 out of 10 attempt will shows the exception.

citrus-context.xml (mock server configuration)

```
<citrus-ws-server id="soapJaxwsServer" port="13080" auto-start="true" timeout="600000" 
root-parent-context="true" resource-base="src/citrus/resource" interceptors="clientInterceptors"/>
```
citrus-ws-server.xml

```
<bean id="defaultWsEndpoint" class="com.consol.citrus.ws.server.WebServiceEndpoint">
     <property name="endpointAdapter" ref="emptyResponseEndpointAdapert"/>
</bean>
<citrus:empty-response-adapter id="emptyResponseEndpointAdapter" />
```
mytest.xml
```

```
When i got the exception, response is coming properly. 
As per my understand, it is generating RACE condition somewhere in citrus-core code, might be it is in QueueChannel.

Could you please suggest how i can moved out from this issue.

(sorry i am unable to put the logs at this time)

Thanks,
kapil

**Comment by christophd** [comment]
The information given in your issue description is giving me headaches. You give an empty `mytest.xml` - why that? You give the `citrus-ws-server.xml` configuration but I do not see that `soapJaxwsServer` is referencing that configuration anywhere. Are you overwriting the `defaultWsEndpoint` bean? 

You define a static empty response endpoint adapter in that configuration on the `defaultWsEndpoint` and at the same time you want to receive the request in your test? This is not working as the empty response adapter will always take the request first. Your test will always get `ActionTimeoutException` then.

Please clarify the configuration and test code so I can have a look at this, thanks!
