### ISSUE TITLE
Multipart file upload.

### ISSUE THREAD

**Issue by ahaquek** [christophd/citrus#304]
Multipart file upload is not supported in citrus. Even in latest version 2.7.2 it is not supported. Please let me know any plan of Multipart file uploading by POST request in future release.

**Comment by ahaquek** [comment]
Please reply on this issue.

**Comment by christophd** [comment]
I have to investigate if this is possible right now via Spring RestTemplate or Apache Camel integration. Please kindly give me some time for that.

**Comment by faisalferoz** [comment]
There is a PR for above #321
