### ISSUE TITLE
Mail server not automatically responding

### ISSUE THREAD

**Issue by gucce** [christophd/citrus#305]
### Problem

The [Citrus documentation](http://www.citrusframework.org/reference/2.7.2/html/index.html#mail-server) on the mock mail server states:

> Regardless of how the mail message has passed the validation the Citrus SMTP mail server will automatically respond with success codes (SMTP 250 OK) to the calling client. This is the basic Citrus mail server behavior where all client connections are accepted an all mail messages are responded with SMTP 250 OK response codes.

This is not true. If you don't respond explicitly with status code 250 the calling client will throw an error.

**UPDATE (11/13/2017)** I had a second issue with my mail server. At the end of the test I stop the mail server immediately, which leads to an error in the SMTP client. It seems that the answer is not sent out before the server stops. This can be remedied with a `sleep` to give the mail server time to answer.

```xml
<!-- without this sleep the server will stop before the last acknowledge has been sent causing an error in the SMTP client. -->
<sleep seconds="3"/>

<stop server="loggingSmtpServer">
    <description>Stop mock mail server</description>
</stop>
```

### Example

Mail server configuration

```xml
<citrus-mail:server id="mockSmtpServer" port="50505" split-multipart="true" auto-accept="true"/>
```

Receive action

```xml
<receive endpoint="mockSmtpServer" timeout="5000">
    <message>
        <validate>
            <script type="groovy">
                assert true
            </script>
        </validate>
    </message>
</receive>
```

The following `send` **must** be explicitly stated, it is **not done automatically**.
**Note** This is also how it is done in the [Citrus mail sample](https://github.com/christophd/citrus-samples/tree/master/sample-mail).

```xml
<send endpoint="mockSmtpServer">
    <message>
        <payload>
            <mail-response xmlns="http://www.citrusframework.org/schema/mail/message">
                <code>250</code>
                <message>OK</message>
            </mail-response>
        </payload>
    </message>
</send>
```

Without the explicit `send` we can see there is no response:

```
15:49:55,352 WARN  annelEndpointAdapter| Reply timed out after 1000ms. Did not receive reply message on reply channel
15:49:55,352 DEBUG annelEndpointAdapter| Did not receive reply message - no response is simulated
```

### Solution

Verify why the response is not automatically sent as stated in the documentation. Alternative: remove this paragraph from the documentation and replace it with a section telling that you have to respond with a 250.

**Comment by christophd** [comment]
Mail server has to wait some time (default 5000ms - configurable via timeout setting) before responding with automatic 250 OK. Maybe your client is raising the error because of smaller timeout.

**Comment by gucce** [comment]
Which timeout are you referring to? I have set a timeout of 5000ms in the `receive` action because it takes a couple of seconds for the system to send out the e-mail I want to receive.  
The `mockSmtpServer` itself doesn't have a configured timeout. It sets the timeout to 1000ms by default, as I have checked in the code.  
I understand, that the server only waits 1000ms for a reply to occur, so obviously there is a mismatch between the receive timeout and the server timeout. Which explains the message `Reply timed out after 1000ms. Did not receive reply message`. However, even if I set the server timeout to 10000ms, so it waits long enough on the answer, I still get the message `Reply timed out after 10000ms. Did not receive reply message`.

**Comment by christophd** [comment]
As I understand you do not explicitly set a response in your test case. So the server waits until the timeout is hit after X ms. My point is that the calling mail client has a timeout < X set so the client is not waiting for the response the required X amount of milliseconds.

**Comment by gucce** [comment]
Finally, I came around trying the mail server from the [citrus-samples repository](https://github.com/christophd/citrus-samples/tree/master/sample-mail). I didn't encounter this problem there. I guess it has to do with the email client, which is some Tibco implementation.

I'll close this ticket, since this is not easily reproducible.
