### ISSUE TITLE
Change format timezone

### ISSUE THREAD

**Issue by SimonedG** [christophd/citrus#309]
Hello,

Our middleware automatically creates a timestamp like this "+01:00" whereas Citrus automatically creates a timestamp likes this "+0100". Because of this our testscripts keep failing. Has someone a solution for this issue?

Thanks in advance,
Kind regards Simone

**Comment by christophd** [comment]
In case you are using citrus:currentDate() function you can give a date format string so the function creates the needed timestamp format.
