### ISSUE TITLE
Upgrading from 2.6.2 to 2.7.2: HTTP basic authentication doesn't work

### ISSUE THREAD

**Issue by binhthai** [christophd/citrus#312]
Hi,

I am upgrading Citrus 2.6.2 to 2.7.2 and facing an issue regarding HTTP basic authentication.
I get HTTP-401.
Example of a config (Citrus 2.6.2):
```
<bean id="securityHandler" class="com.consol.citrus.http.security.SecurityHandlerFactory">
    <property name="users">
        <list>
            <bean class="com.consol.citrus.http.security.User">
                <property name="name" value="${server.user}"/>
                <property name="password" value="${server.password}"/>
                <property name="roles" value="${server.user}"/>
            </bean>
        </list>
    </property>
    <property name="constraints">
        <map>
            <entry key="/*">
                <bean class="com.consol.citrus.http.security.BasicAuthConstraint">
                    <constructor-arg value="${server.user}"/>
                </bean>
            </entry>
        </map>
    </property>
</bean>
```

As per latest `citrus-samples/sample-http-basic-auth` it seems that with Citrus 2.7.2 we need to pass an `org.eclipse.jetty.security.HashLoginService` to the security-handler.
I'm not sure whether the assumption is correct and would like to ask for an 'official guide'.
It would be nice if you could provide an example config (XML-based).

Thank you very much in advance

Best regards,

Binh

**Comment by christophd** [comment]
Duplicate to #290

**Comment by christophd** [comment]
You can use the workaround described in #290 and use it in your XML config as follows:

    <bean class ="com.example.HttpServerBasicAuthConfig"/>

**Comment by binhthai** [comment]
Thank you very much Christoph!
You are too fast!
