### ISSUE TITLE
How to ignore text parts in plain text validator

### ISSUE THREAD

**Issue by armandoruizgonzalez** [christophd/citrus#313]
In XML it is easy, because there is a tag called @ingore, but in PlainTextMessageValidator it does not exist.
Example: in my flat plot I have from position 12 to 22 a field that is dynamic that is the date, then the plot when I compare it I get error.

Thank's a lot

**Comment by christophd** [comment]
You can make use of the String validation matcher such as @startsWith()@, @endsWith()@ in oder to check that the plaintext is as expected. That solution might be quite limited though.

The validation of your plaintext payload is very specific to your needs. There is no generic way to ignore this piece of character sequence other than writing a custom PlainTextMessageValidator that is aware of ignoring that particular sequence block. Writing a custom validator based on an existing validator is not very hard to accomplish. I think this should be the best solution for you.

**Comment by christophd** [comment]
I have added a simple way to do this kind of ignore operation which is based on the `@ignore@` placeholder that should be placed at the exact same position in the text.

## Source text
    Your current id is '1234567890'
## Control text
    Your current id is '@ignore@'

This will ignore the exact same word in the source text. A word is specified by non-word characters (\\W) in Java. Also you can give the exact amount of characters to ignore:

## Source text
    Your current id is '#12345-67890'
## Control text
    Your current id is '@ignore(12)@'

This will ignore exactly *12* characters starting from the position of the `@ignore@` expression.

In general this requires you to know the exact text structure including all whitespace characters.

**Comment by benszabo** [comment]
Hey Christopher, I am working with a similar situation with dynamic data in a plain text jms message. I need to do something like: receive(message).payload("@ignore(17)@@startsWith('U')@");

validating specific character(s) ignoring everything before and pretty much after, but there is too much system produced data within the message to specify before or after characters.

I don't see much going on with plain text matchers and cant find samples with creating a custom one. With that aside, is there any way to achieve what I was trying to do? Chaining or even nesting validation matchers?
