### ISSUE TITLE
SQL action not executing statements income from variables or starting different from SELECT keyword 

### ISSUE THREAD

**Issue by bambuchastudent** [christophd/citrus#333]
Create XML test action:
`<create-variable>
    <variable name="${VARIABLE_NAME} value = "SELECT 1 FROM DUAL" />
</create-variable>
`
`<sql datasource="datasource">
    <statement>${VARIABLE_NAME}</statement>
</sql>`

Run the test and get an exception
`
Caused by: com.consol.citrus.exceptions.CitrusRuntimeException: Missing keyword SELECT in statement: "${VARIABLE_NAME}"
	at com.consol.citrus.actions.ExecuteSQLQueryAction.validateSqlStatement(ExecuteSQLQueryAction.java:293)
`
Do the query validation is really necessary at this point?

**Comment by christophd** [comment]
Your code example is having some syntax errors like `create-variable` instead of `create-variables` and some missing ending quotes around `name="${VARIABLE_NAME}`.

Also I can not reproduce that behavior on my local machine. This is what works fine for me:

    <create-variables>
        <variable name="statement" value="SELECT 1 FROM DUAL"/>
    </create-variables>

    <sql datasource="testDataSource">
        <statement>${statement}</statement>
    </sql>

I was testing that with Citrus 2.7.3

**Comment by bambuchastudent** [comment]
Ok, the problem present in 2.7.3 and now seems is fixed
from com.consol.citrus.actions.ExecuteSQLQueryAction:
```
protected void executeStatements(List<Map<String, Object>> allResultRows, Map<String, List<String>> columnValuesMap, TestContext context) {
        for (String stmt : statements) {
            validateSqlStatement(stmt); -- problem
            final String toExecute;
            ...
```
