### ISSUE TITLE
Can we write a Kafka Topic integration test case using Citrus ?

### ISSUE THREAD

**Issue by nimskhan** [christophd/citrus#335]
We have services having Kafka Topics integration. Is there support to write a Kafta topic integration test case using citrus ?

**Comment by FMAOuroboros** [comment]
Hi!
There is currently no direct support for Kafka as an endpoint as far as I know.
But there is an issue for a Kafka endpoint integration, you could vote for. https://github.com/christophd/citrus/issues/152

Nevertheless, there is an older issue, where @christophd mentioned the possibility to connect to Kafka using the Apache Camel bridge. Maybe you could try this out.
https://github.com/christophd/citrus/issues/53

**Comment by christophd** [comment]
@FMAOuroboros is right - currently no support for Kafka as a Citrus endpoint. But you can use the Apache Camel integration for sending/receiving messages with Kafka in Citrus right now (http://www.citrusframework.org/reference/2.7.3/html/index.html#apache-camel). Bit more configuration as you need a Apache Camel route but it should be working for you. 

Let me know if you need some more details about that.

**Comment by nimskhan** [comment]
@FMAOuroboros  Thanks for sharing details. Sure, I will vote and will try **Apache Camel bridge**.
@christophd Thank you so much. I will try Apache Camel integration. Will let you know accordingly!

**Comment by Cs4r** [comment]
@nimskhan any updates on this? were you able to create a citrus integration test that uses kafka via the camel bridge?

**Comment by FMAOuroboros** [comment]
Hey @nimskhan,

Have you been able to solve your problem? 

BR, 
Sven

**Comment by FMAOuroboros** [comment]
I assume that the problem has been solved.

@Cs4r It would be great, if you could share details about whether the camel bridge worked for you with kafka. If you need any help, please just open an issue. =)

BR,
Sven
