### ISSUE TITLE
Response Status code is no longer validated after update to 2.7.1

### ISSUE THREAD

**Issue by petyam** [christophd/citrus#340]
After updating my citrus version from 2.6 to 2.7.3 all my tests that were failing due to the returned status code not being the expected one all of a sudden started passing.
After checking I could see still that I receive 200 but citrus_http_status_code seemed to be set to 401(the status I set for expected)
I have now left version 2.7 which seems to be working and I checked that with 2.7.1 is ignoring the status
I'm using dsl runner

    runner.http(httpActionBuilder -> {
            HttpClientResponseActionBuilder response = httpActionBuilder
                    .client(serviceName).receive()
                    .response(HttpStatus.valueOf(status))
                    .messageType(MessageType.JSON);       
        });

**Comment by FMAOuroboros** [comment]
Hi!

Unfortunately I'm unable to reproduce your problem. I tested Citrus 2.6 and 2.7.3 with an injected test runner. I also modified the tests to fail on purpose to validate that the HTTP status code is evaluated correctly.
Here is a sample output when I changed the expected response code to `404` to break the test.
```
[ERROR] testPost(com.consol.citrus.samples.todolist.TodoListIT)  Time elapsed: 0.585 s  <<< FAILURE!
com.consol.citrus.exceptions.TestCaseFailedException: Validation failed: Values not equal for header element 'citrus_http_status_code', expected '404' but was '302'
        at com.consol.citrus.samples.todolist.TodoListIT.testPost(TodoListIT.java:54)
```

Here are the tests cases. These tests are modified versions of the `ToDoListIT` within the `sample-http` module of the [citrus-samples](https://github.com/christophd/citrus-samples) repository.

**With Citrus 2.6**
```java
public class TodoListIT extends TestNGCitrusTest {

    @Autowired
    private HttpClient todoClient;

    @Test @Parameters("runner")
    @CitrusTest(name = "TestNGCitrusTest")
    public void testPost(@Optional @CitrusResource TestRunner runner) {
        runner.variable("todoName", "citrus:concat('todo_', citrus:randomNumber(4))");
        runner.variable("todoDescription", "Description: ${todoName}");

        runner.http(httpActionBuilder ->
                httpActionBuilder.client(todoClient)
                    .post("/todolist")
                    .contentType("application/x-www-form-urlencoded")
                    .payload("title=${todoName}&description=${todoDescription}"));

        runner.http(httpActionBuilder ->
                httpActionBuilder.client(todoClient)
                   .response(HttpStatus.valueOf(302)));
    }
}
```

**With Citrus 2.7.3**
```java
public class TodoListIT extends TestNGCitrusTest {

    @Autowired
    private HttpClient todoClient;

    @Test @Parameters("runner")
    @CitrusTest(name = "TestNGCitrusTest")
    public void testPost(@Optional @CitrusResource TestRunner runner) {
        runner.variable("todoName", "citrus:concat('todo_', citrus:randomNumber(4))");
        runner.variable("todoDescription", "Description: ${todoName}");

        runner.http(httpActionBuilder ->
                httpActionBuilder.client(todoClient)
                    .send()
                    .post("/todolist")
                    .contentType("application/x-www-form-urlencoded")
                    .payload("title=${todoName}&description=${todoDescription}"));

        runner.http(httpActionBuilder ->
                httpActionBuilder.client(todoClient)
                    .receive()
                    .response(HttpStatus.valueOf(302)));
    }
}
```

So I would like to ask you to double check whether your test implementation is matching the SUT behavior. If you can't find any mismatching, it would be great if you could provide some more details about your test scenario.

**Comment by petyam** [comment]
citrus 2.7 <com.consol.citrus.dsl.runner> Nested exception is: 
com.consol.citrus.exceptions.ValidationException: Validation failed: Values not equal for header element 'citrus_http_status_code', expected '401' but was '200'
same test I just changed citrus version in the pom to 2.7.3
I get 200 again 
14:54:20,746 DEBUG ingClientInterceptor| Received Http response message
14:54:20,746 DEBUG    Logger.Message_IN| HTTP/1.1 200 OK
Server:nginx
Date:Fri, 02 Mar 2018 14:48:48 GMT
Content-Type:application/json
Content-Length:2266
14:54:20,752 DEBUG TextMessageValidator| Control message:
HTTPMESSAGE [id: 98710b8a-224d-4fea-a309-64512dfeee62, payload: ][headers: {citrus_message_id=98710b8a-224d-4fea-a309-64512dfeee62, citrus_message_timestamp=1520002460750, citrus_http_status_code=401, citrus_http_reason_phrase=UNAUTHORIZED}]
So with 2.7.3 the test Passes when it should have failed

As I said no code has been changed at all just citrus version in the pom file

**Comment by FMAOuroboros** [comment]
Hi

Thank you for providing the console output. From the part you've provided it's clearly noticeable that the status codes are different and the test should have failed.
Would it be possible for you to provide the complete console output with the test case attached for further investigation?
I suppose that this behavior has something to do with the setup of your test.

BR,
Sven

**Comment by christophd** [comment]
Hi, 

besides giving the complete log output it may be interesting to get the application context configuration, too.

Do you have customized message validators in your project? Maybe you have to adjust the default message validator chain in Citrus? Also see #201 and https://github.com/christophd/citrus/commit/44baa2da77216157e4f94a4fd82a9a9ba1bbe153

Regards,
Christoph

**Comment by christophd** [comment]
If you have custom message-validators set please make sure to include

**defaultMessageHeaderValidator**: com.consol.citrus.validation.DefaultMessageHeaderValidator

    <citrus:validator ref="defaultMessageHeaderValidator"/>

**Comment by petyam** [comment]
I have just added 
<citrus:validator ref="defaultMessageHeaderValidator"/> in my citrus-context.xml and it started working!

Thanks a lot for your help
