### ISSUE TITLE
Add ".headers" declaration that takes a Map for validation

### ISSUE THREAD

**Issue by sburkard** [christophd/citrus#345]
Currently one can validate headers by adding `.header(name, value)` declarations. 

For building nice TestBehavior classes it would be great to have a `.headers(Map<String, Object>)` declaration. 

It would allow something like this in a TestBehavior implementation:  

        receive(action -> action.endpoint(jmsEndpoint)
                .payload(messageResource)
                .headers(headerMap)

The problem with the single header declaration is, that I cannot apply a variable number of them to the TestBehavior:

        receive(action -> action.endpoint(jmsEndpoint)
                .payload(messageResource)
                // fixed number of header checks
                .header(header1, value1)
                .header(header2, value2)

**Comment by FMAOuroboros** [comment]
Hi!

Thank you for your input! Even with a fixed amount of headers, a header map could be useful, if you have to validate a lots of headers that are messing up your test step definition. A map could enhance readability of those test cases.

I'm also curious about your use case for variable amounts of headers.
So you have a test case where you get a variable amount of headers from somewhere in your test and you want to verify that all headers are transported to another system?

BR,
Sven

**Comment by FMAOuroboros** [comment]
Hi Stephan!

Ah! Now I see the `TestBehavior` :smile:. Just overlooked it in your initial suggestion. My fault.
Thank you for the insight into your project. Really cool setup! I find it always interesting how people use Citrus and it provides valuable information on how Citrus should be developed to improve the user experience when writing tests.

BR,
Sven
