### ISSUE TITLE
Copying ZIP-Files

### ISSUE THREAD

**Issue by SvenRop** [christophd/citrus#351]
Hello Christoph,
I have a problem with copying .zip-files via an file-endpoint. The .zip file is after sending it via an file-endpoint bigger than before and it is corrupt.

Usecase: Starting a process with a filepoller. The process is checking the .zip-file and is unzipping it.

Is there a way for processing the zip file on this or on an other way?

Best regards,

Sven

**Comment by christophd** [comment]
Hi Sven, can you please share some code/configuration for your file-endpoint? I assume you are using some Apache Camel file endpoint here as Citrus does not provide a native file endpoint yet.

**Comment by FMAOuroboros** [comment]
Hey @SvenRop.

We're you able to solve the problem?

BR, 
Sven

**Comment by SvenRop** [comment]
Hallo Christoph, hallo Sven, 

entschuldigt dass ich mich erst jetzt melde. Wir haben Function gebaut um die Zip-Files zu kopieren.
Vielen Dank für eure Hilfe.

Grüße
Sven

**Comment by FMAOuroboros** [comment]
Hallo Sven, 

kein Problem! Schön, dass ihr das Problem lösen konntet!

Viele Grüße,
Sven
