### ISSUE TITLE
Remote Citrus test report contains double entries

### ISSUE THREAD

**Issue by codemental** [christophd/citrus#355]
Hi Christoph,

during remote test execution (Citrus tests inside a `.war`) with the new `citrus-remote-maven-plugin` I have noticed that the Citrus test report contains double entries.

```
INFO  | CITRUS TEST RESULTS
INFO  | 
INFO  |  UserManagementServiceIT.createUser .......................... SUCCESS
INFO  |  UserManagementServiceIT.createUser .......................... SUCCESS
INFO  |  UserManagementServiceIT.createUserConflict .................. SUCCESS
INFO  |  UserManagementServiceIT.createUserConflict .................. SUCCESS
INFO  |  UserManagementServiceIT.deleteUser .......................... SUCCESS
INFO  |  UserManagementServiceIT.deleteUser .......................... SUCCESS
INFO  |  UserManagementServiceIT.deleteUserNotFound .................. SUCCESS
INFO  |  UserManagementServiceIT.deleteUserNotFound .................. SUCCESS
INFO  |  UserManagementServiceIT.editUser ............................ SUCCESS
INFO  |  UserManagementServiceIT.editUser ............................ SUCCESS
INFO  |  UserManagementServiceIT.getAllUsers ......................... SUCCESS
INFO  |  UserManagementServiceIT.getAllUsers ......................... SUCCESS
INFO  | 
INFO  | TOTAL: 12
INFO  | FAILED:   0 (0.0%)
INFO  | SUCCESS:  12 (100.0%)
```
I have only 6 tests but the report contains 12.
I have used a port listener and checked the HTTP requests. The tests do not appear to be executed twice. It seems that only the report itself is buggy.

Also, if I leave the app running and execute the tests with the plugin again, the report will contain 24 test results.

**Comment by christophd** [comment]
This is because you executed tests two times at the same remote server instance without redeployment. The remote server caches old results and does not clear test results for each test run.

**Comment by codemental** [comment]
The output is from the very first run. If I execute the tests again on the same remote server without redeployment, the output will show me 24 tests. If I do that a third time, 36 tests, and so on.

**Comment by christophd** [comment]
Must have been a duplicate add of the reporter in test suite listeners. I changed the logic in test suite listeners in order to prevent this duplicates when adding new reporters
