### ISSUE TITLE
Dynamic creation of HttpClient object

### ISSUE THREAD

**Issue by rbkumar88** [christophd/citrus#360]
Hi ,

Is there any way we can create multiple HttpClient objects with different bean names and endpoint uri. Say, I want to read a properties file and create these HttpClient beans (on the fly) when the application starts.
e.g., test.properties
```
clientEndpoint1=http://localhost:8181/
clientEndpoint2=http://localhost:8282/
....
```

Thanks

**Comment by christophd** [comment]
I would go for dynamic endpoint creation with `@CitrusEndpoint` and `@HttpClientConfig` as suggested by @FMAOuroboros 

As an alternative you could also use dynamic endpoint uri as described in http://www.citrusframework.org/reference/2.7.4/html/index.html#dynamic-endpoint-components

So you can just use:

    http().client("http://localhost:8181/").send().post()...

You could then get the ports from property file and load those as test variables. Reading the property file and creating endpoints directly out of that is not supported though.

**Comment by FMAOuroboros** [comment]
Hi @rbkumar88!

Did you have the opportunity to try out our suggestions? Were we able to answer your question or is something unclear? It would be great if you could provide some feedback. 

BR, 
Sven

**Comment by FMAOuroboros** [comment]
Hi @rbkumar88!

I'm glad to hear that you were able to solve the problem!

BR,
Sven
