### ISSUE TITLE
Payload not getting latest value while validating

### ISSUE THREAD

**Issue by Vineet-happy** [christophd/citrus#368]
Hi CITRUS Community,

I have a some weird problem when I am loading payload into queue.

I have 2 test cases @TestCase1 and @TestCase2 and I am using the same stored procedure to fetch blob from DB and store into xml file.

In each test case I validate the stored xml file with expected xml file by sending it to a test queue and while receiving I am validating it.

Now the problem is both these XML files are different but while sending it takes the old xml generated by previous run and my test case is failing.Please suggest a way to overcome this.

code snipped is as provided below.

I feel that I am facing problem while loading the stored xml.

Test cases are as provided below.
Quick resolution will be of great help.

	@Test
        @CitrusTest
       public void XDSL_INTERNET_ADD_1() {
			variable("rododReqId", "citrus:randomNumber(10)");
    		variable("servicePointId","144638005");
    		variable("FBNumber","FB144638005");
    		variable("DownLink","30Mb/S");
    		variable("ServiceProfileID","1");
			variable("operation","'%getCustomerDetails%'");
			variable("operation_cash","'%addCopperService%'");
    		purgeEndpoints().endpointNames("jmsEndpoinReq", "jmsEndpointResp", "jmsEndpointSync","natfragaResponsequeue","cashAckResponsequeue","cashResponsequeue","jmsEndpointNetAdminResp","jmsEndpointTestingQueue"); // multiple endpoints
            send("jmsEndpoinReq").payload(new ClassPathResource("templates/XDSL_ADD_Address.xml")); 
		    receive("jmsEndpointResp").payload(new ClassPathResource("templates/ValidSyncResponse.xml")).ignore("RequestHeader");
			sleep(20000);
			echo("${rododReqId}");
			sleep(20000);
			sql(dataSource).statement("call cw.procPrintHelloWorld(${rododReqId},${operation});");
			sleep(60000);
		    send("jmsEndpointSync").payload(new FileSystemResource("C:/Users/eviparv/Latest_Citrus/Telia_Testcase/modules/XDSL/src/test/resources/templates/MyXML1.xml"));
		    sleep(60000);
			receive("jmsEndpointSync").payload(new ClassPathResource("templates/ExpectedNatfrgaRequest1.xml")).ignore("Header");
			send("natfragaResponsequeue").payload(new ClassPathResource("templates/Natfraga_Address_Response.xml"));
			sleep(30000);
 			query(dataSource)
			.statement("select max(ORDER_ID) as order_id from cwmessagelog where ordernumber = '${rododReqId}' and  operation like '%Copper%'")
		    .extract("order_id","rododReqId1");
		    sleep(60000);
			
			sql(dataSource).statement("call cw.procPrintHelloWorld1(${rododReqId},${operation_cash});");
			sleep(150000);
			//Problem with this while sending the payload taking the MyXML file generated from next test case(XDSL_INTERNET_ADD_2),though the file contains new payload information
		    send("jmsEndpointNetAdminResp").payload(new FileSystemResource("C:/Users/eviparv/Latest_Citrus/Telia_Testcase/modules/XDSL/src/test/resources/templates/MyXML.xml"));
			
			}
			
			@Test
        @CitrusTest
       public void XDSL_INTERNET_ADD_2() {
			variable("rododReqId", "citrus:randomNumber(10)");
    		variable("servicePointId","144638005");
    		variable("FBNumber","FB144638005");
    		variable("DownLink","30Mb/S");
    		variable("ServiceProfileID","1");
			//variable("operation","'%getCustomerDetails%'");
			variable("operation_cash","'%addCopperService%'");
    		purgeEndpoints().endpointNames("jmsEndpoinReq", "jmsEndpointResp", "jmsEndpointSync","natfragaResponsequeue","cashAckResponsequeue","cashResponsequeue","jmsEndpointNetAdminResp","jmsEndpointTestingQueue"); // multiple endpoints
            send("jmsEndpoinReq").payload(new ClassPathResource("templates/XDSL_ADD_Number.xml")); 
		    receive("jmsEndpointResp").payload(new ClassPathResource("templates/ValidSyncResponse.xml")).ignore("RequestHeader");
			sleep(50000);
 			query(dataSource)
			.statement("select max(ORDER_ID) as order_id from cwmessagelog where ordernumber = '${rododReqId}' and  operation like '%Copper%'")
		    .extract("order_id","rododReqId1");
		    sleep(60000);
			sql(dataSource).statement("call cw.procPrintHelloWorld1(${rododReqId},${operation_cash});");
			sleep(150000);
			//Problem with this while sending the payload taking the MyXML file generated from next test case(XDSL_INTERNET_ADD_1),though the file contains new payload information
		    send("jmsEndpointTestingQueue").payload(new FileSystemResource("C:/Users/eviparv/Latest_Citrus/Telia_Testcase/modules/XDSL/src/test/resources/templates/MyXML.xml"));
			}

**Comment by christophd** [comment]
This is because you are using test designer Java DSL. So the FileSystemResource is read at the very beginning of the test setup and loaded into memory. You need to use test runner Java DSL. This will fix your problem as the file system resource is then loaded at test runtime.

**Comment by Vineet-happy** [comment]
This solved the problem..thanks

**Comment by BanuBizBitch** [comment]
I have the same problem. The FileSystemResources are read at the very beginning and changes I make in the subsequent request calls are not updated :( . I am using test runner though. I also use cucumber BDD. Please help. Anyone.....:(
public TestContext getTestContext()
    {
        if (testContext == null)
        {
            runner.run(new AbstractTestAction() {
                @Override
                public void doExecute(TestContext context) {
                    testContext = context;
                }
            });
        }
        return testContext;
    }

    @Given("^I set path: \"([^\"]*)\" for all the request payloads and set variables$")
    public void i_set_path_and_variables(String path) throws Throwable
    {
        this.path = path;
        document = null;
    }

    @And("^I place a valid request with \"([^\"]*)\" for client \"([^\"]*)\"$")
    public void i_place_a_valid_request( String payload, String client) throws Throwable {
        System.out.println(path + payload);
        runner.soap(
                a -> a.client(client).send().payload(new ClassPathResource(path + payload)));
    }
