### ISSUE TITLE
String[] parameters to Java call inside template are re-used

### ISSUE THREAD

**Issue by matthew-wilson** [christophd/citrus#37]
If there is a <java> action inside a <template>, then any "String[]" parameters passed to the Java method seem to get their values cached. ie if I call the template multiple times, then the parameters from the first call get used in all subsequent instances too.

This only seems to happen for String[] parameters (not String parameters) and only when the java call is inside a tepmlate.

**Comment by matthew-wilson** [comment]
https://gist.github.com/matthew-wilson/f2753850ff6362d55483

**Comment by christophd** [comment]
Thank you for pointing to this! This is a bug in java test action implementation. The String array was not deeply copied before resolving variables. Fixed it, thanks!
