### ISSUE TITLE
Citrus adapter 2.0 not available in maven repo

### ISSUE THREAD

**Issue by mujahedsyed** [christophd/citrus#39]
Hi,

The citrus-adapter 2.0 maven dependency is not available to download in the maven repo:

http://labs.consol.de/maven/repository/com/consol/citrus/citrus-adapter/

Full dependency info:
	<dependency>
			<groupId>com.consol.citrus</groupId>
			<artifactId>citrus-adapter</artifactId>
			<version>2.0</version>
		</dependency>

Is this dependency not neeeded for 2.0 ?

Thanks,
Regards

**Comment by christophd** [comment]
Hi,

citrus-adapter is no longer needed. Classes and API went to citrus-core with 2.0

So just remove this dependency from your Maven POM

**Comment by mujahedsyed** [comment]
Thank you for the response.
