### ISSUE TITLE
Validating timestamp value in interval

### ISSUE THREAD

**Issue by bassmake** [christophd/citrus#42]
It is hard to validate timestamp value exactly, but in most cases tester can expect timestamp in some interval. Especially in combination with citrus:currentDate().
`<Timestamp>@between(2001-12-17T09:30:47.0Z,2001-12-17T09:30:50.0Z)@</Timestamp>`

I haven't found anything like this in the documentation so I assume this is not yet possible.

**Comment by christophd** [comment]
No there is no such validation matcher available, I'll see if we can have something like this in upcoming versions

**Comment by bassmake** [comment]
i am drunk

On Tue, Jul 14, 2015 at 10:53 PM, Christoph Deppisch <
notifications@github.com> wrote:

> No there is no such validation matcher available, I'll see if we can have
> something like this in upcoming versions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christophd/citrus/issues/42#issuecomment-121382278>.
>



-- 
Miroslav Matejovsky

**Comment by christophd** [comment]
Done, see commit https://github.com/christophd/citrus/commit/1aecd240053489be0867623a81c88c98daaf7310
