### ISSUE TITLE
Nested iterate conditions not evaluated as expected

### ISSUE THREAD

**Issue by matthew-wilson** [christophd/citrus#44]
If I have nested <iterate> elements in a Citrus test, then the inner loop only executes during the first iteration of the outer loop. Even if I use <create-variables> to reset the variable associated with the inner loop to 0, the content of the inner loop is not executed.

        <actions>
          <iterate condition="i lt= 5" index="i">
            <create-variables>
              <variable name="j" value="0"/>
            </create-variables>
            <iterate condition="j lt= 3" index="j">
             <echo>
              <message>i=${i} j=${j}</message>
             </echo>
            </iterate>
          </iterate>
        </actions>

This only echoes the following messages:
i=1 j=1
i=1 j=2
i=1 j=3

When i is greater than 1 the condition "j lt= 3" continues to evaluate as false.

**Comment by christophd** [comment]
Which version are you using? This one has already been fixed in version 2.2 (see https://citrusframework.atlassian.net/browse/CITRUS-245)

**Comment by christophd** [comment]
wrote a test for that which is working fine on 2.2

			<iterate condition="i lt= 5" index="i">
				<create-variables>
					<variable name="outerLoop">
							<value>
								<script type="groovy">(${outerLoop} + 1)</script>
							</value>
					</variable>
				</create-variables>
				<iterate condition="j lt= 3" index="j">
					<create-variables>
						<variable name="innerLoop">
							<value>
								<script type="groovy">(${innerLoop} + 1)</script>
							</value>
						</variable>
					</create-variables>
					<echo>
						<message>i=${i} j=${j}</message>
					</echo>
				</iterate>
			</iterate>

			<groovy>
				println context.getVariable("outerLoop")
				println context.getVariable("innerLoop")

				assert context.getVariable("outerLoop").equals("5")
				assert context.getVariable("innerLoop").equals("15")
			</groovy>

**Comment by matthew-wilson** [comment]
I'm on 2.0. I didn't realise there was a newer version - sorry.
