### ISSUE TITLE
Assertion failures during parallel don't cause test failures

### ISSUE THREAD

**Issue by matthew-wilson** [christophd/citrus#45]
Sometimes during <parallel> sections, an assertion fails, but does not cause the test as a whole to fail.

see eg https://gist.github.com/matthew-wilson/423b6a8b8788e8b83a53

The test shows the assertion failure:
Exception in thread "Thread-3" Assertion failed: 

assert 123 == 456
           |
           false

but the overall result is a pass:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

If I take out "&lt;parallel&gt;" then the test fails, as expected.

**Comment by christophd** [comment]
This is a good sample, thank you.

Actually the "assert" Java key word in your groovy script causes a java.lang.AssertionError which is not caught within failure detection in parallel block. If we change the template and groovy script to following:

    <template name="textMatch">
      <groovy>
        <![CDATA[
          import com.consol.citrus.exceptions.CitrusRuntimeException
          if (${text1} != ${text2}) {
            throw new CitrusRuntimeException("Text did not match")
          }
        ]]>
      </groovy>
    </template>

Here everything is working fine as the groovy script raises some kind of Java exception. I will fix the failure detection in parallel block so assertion errors are also detected as test failure. Thanks for your sample code, this is great!
