### ISSUE TITLE
JSON data dictionary throws NullPointerException

### ISSUE THREAD

**Issue by varunmulloli** [christophd/citrus#47]
I have a JSON data dictionary like this:
```
<citrus:json-data-dictionary id="sampleDD">
    <citrus:mappings>
        <citrus:mapping path="id" value="2" />
    </citrus:mappings>
</citrus:json-data-dictionary>
```

And my `<send>` action looks like this:
```
<send endpoint="sampleEndpoint">
    <message data-dictionary="sampleDD" type="json">
		<data>
			{
				"id": 1,
				"name": "abcd",
				"tag": null
			}
		</data>
    </message>
</send>
```
I presume that this is a valid JSON, even though one of the key has a value null. While running the code, I get an NPE.

**Comment by christophd** [comment]
I was able reproduce this error, thanks! This is an issue with the null value indeed. Will fix this with 2.4 version. Thanks!
