### ISSUE TITLE
XPath validation asserts only on first element of the expression result

### ISSUE THREAD

**Issue by donat-mueller** [christophd/citrus#49]
When message reply validation is done with xpath, only the first node from a NodeList or NodeSet is validated. The xpath evaluation signature  
`public Object XPathExpression:evaluate(Object item, QName returnType) throws XPathExpressionException;`
returns the first node in case the result is a collection.

Example: `<validate path="//document/status/errorMsg" value="#ok"></validate>`
Expected all `document/status/errorMsg` elements are tested against the expected value.

**Comment by christophd** [comment]
You are right I see your point. What if we add something like this:

`<validate path="//document/status/errorMsg" value="#ok,#ok,#not-ok" result-type="node-set" />`

With the node-set result type the expression result value is translated to a comma delimited string containing all values from the NodeList. The validation is then even more powerful as we can have different values checked in the node list.

**Comment by christophd** [comment]
With a little XPath magic you can do the validation also with the current code. Have a look at this:

`<validate path="count(//document/status/errorMsg[.= '#ok'])" value="3" result-type="number" />`

We validate the number of found nodes that match the node value '#ok'. That should do the trick for node lists of same node-value. But I think the idea with the node-set validation is worth adding.

**Comment by donat-mueller** [comment]
The last solution works fine for me.
Thanks a lot for your help !
