### ISSUE TITLE
DynamicEndpointUriResolver - Suggestion for query param syntax

### ISSUE THREAD

**Issue by varunmulloli** [christophd/citrus#52]
Hi,

The current syntax for dynamically adding query params for HTTP request is

```
        <header>
            <element name="citrus_query_params" value="param1=value1,param2=value2" />
        </header>
```

which will resolve to something like `http://localhost:8080/test?param1=value1&param2=value2`

I have a use case where the query param value itself contains a comma. With the current setup, that use case is not supported. In line 111 of `DynamicEndpointUriResolver.java`, if the `StringTokenizer` delimiter can be changed to '&', I guess it can support all use cases.

Thanks!

**Comment by christophd** [comment]
The '&' character is also not perfect as delimiter as this is a special character in XML for using entities. You can not use '&' safely in XML. You would have to escape with '&amp;amp;' entity then.

Are you able to upgrade to Citrus 2.4? We have improved Http REST support in this version. So you could define query parameters like this:

    <http:send-request client="httpClient">
      <http:GET path="/customer/${custom_id}">
        <http:params>
          <http:param name="param1" value="value1"/>
          <http:param name="param2" value="value2"/>
        </http:params>
      </http:GET>
    </http:send-request>

This should enable you to have comma values as part of query parameters.
