### ISSUE TITLE
Apache Kafka Support?

### ISSUE THREAD

**Issue by aadrian** [christophd/citrus#53]
Hi,

Any plans for supporting Apache Kafka http://kafka.apache.org/ too?
Quite a few projects use it these days as a faster and more lightweight alternative to a JMS solution.

Thank you.

**Comment by christophd** [comment]
No plans so far but I will definitely have a look at this, thanks for the idea. I will come back to you as soon as I have some news.

**Comment by christophd** [comment]
Another idea that comes to my mind: Have you had a look at the Apache Camel integration within Citrus? Citrus is able to communicate with Apache Camel routes and as Apache Camel has Kafka components you will be able to connect to Kafka using the Apache Camel bridge.

Please have a try as you can do this right away with current Citrus versions. Please let me know if there is any problem with that.

**Comment by aadrian** [comment]
Thanks for your help!
