### ISSUE TITLE
JUnit4CitrusTestDesigner : validateScript doesn't work properly

### ISSUE THREAD

**Issue by arnaud-deprez** [christophd/citrus#58]
Hi,

With JUnit4CitrusTestDesigner, using the following code doesn't not work : 

```java
http().client(enterpriseApiHttpClient)
    .response(HttpStatus.OK)
    .contentType(MediaType.APPLICATION_JSON)
    .messageType(MessageType.JSON)
    .validateScriptType("groovy")
    .validateScript(new ClassPathResource("groovy/customer/ValidateGetCustomers.groovy")))
    .timeout(30000L);
```

It throw a FileNotFoundException for ValidateGetCustomers.groovy even if the file exists. However if I transform this file to a String, it works fine.

Regards

**Comment by christophd** [comment]
Thanks for reporting this one, fixed it by immediately reading file resource content
