### ISSUE TITLE
Provide protected fields or getters in com.consol.citrus.dsl.junit.JUnit4CitrusTestRunner in order to make it easier extendable

### ISSUE THREAD

**Issue by aaschmid** [christophd/citrus#64]
I want to extend the `JUnit4CitrusTestRunner` to add custom operations. Therefore I need various field to be protected:

For example I need a `SendFileBuilder` and `SendFileAction`. Unfortunately, the `applicationContext` is private rather than protected. Of course, I could just `@Autowired` it but this is unnecessary IMHO. 

I also want to store a variable which is available in the `textContext` to a local java variable. Currently, I solved this by creating an action

``` java
public class RetrieveVariableAction extends AbstractTestAction {
    private TestContext context;
    @Override
    public void doExecute(TestContext context) {
        this.context = context;
    }
    public String getVariableValue(String variableName) {
        if (context == null) {
            throw new IllegalStateException(
                    String.format("%s not available, please run the action before retrieve a variable", TestContext.class.getSimpleName()));
        }
        return context.getVariable(variableName);
    }
}
```

which is used the following

``` java
    protected String retrieveVariable(String variableName) {
        return run(new RetrieveVariableAction()).getVariableValue(variableName);
    }
```

If you now also make the `testRunner` protected I could access the `testContext` via `com.consol.citrus.dsl.runner.DefaultTestRunner.createTestContext()`. This is just one possible solution, maybe there is a better one. Do you understand my problem, though? 
I tried to get the `TestContext` from the `applicationContext` but I always got a different one with deeper investigating about the reason.

But, thank you for this framework :-)

**Comment by christophd** [comment]
TestContext is created before test is executed and gets injected as method parameter to all test actions. So if you want to access the context you should add a test action like this:

action(new AbstractTestAction() { ... });

Each test action has a execute method with TestContext as method parameter. You can add your custom logic the inside the test action execute method.

Hope this helps.

**Comment by aaschmid** [comment]
Hi @christophd,
yes, this is clear and this is why I build an ```retriveVariable(String)``` method to get variables from the test context. Are you not willing to just make more information ```protected``` to make the framework more extentable for me?
Cheers,
Andreas

**Comment by christophd** [comment]
This is not a matter of me being willing to do something or not. We should just discuss the need for some new extension point to the framework. Can you please tell me more about your use case scenario?

Maybe I am also giving you more insight to my thoughts: I am thinking that test runner is able to provide protected access to the test context itself quite easy while test designer would have more problems to do so. This is because of designer's nature to just build and prepare all actions before execution.

Citrus offers both test runner and test designer implementation that should be kept more or less equal in capabilities. I would not be happy with test runner giving access to test context while test designer is not. So I have to look at the designer if I can provide access to the context as well. Let me check this

**Comment by aaschmid** [comment]
Ok, this is understandable and a worth thing to think about, consistency over the different approaches. My use cases at the moment are described above and there are not more yet. But I am at the beginning of using Citrus for our E2E-Service-Integration tests. I think we will have to write a lot of custom actions to satisfy our needs and as soon as encounter another problem due to extensibility, I can update this issue.

**Comment by christophd** [comment]
I had a look at this and cam up with a solution via resource injection. So the test context instance can be injected to your test method. I will be very happy to receive your feedback. Read about it here: http://citrusframework.org/reference/html/index.html#testcase-context-injection 

By the way Citrus 2.5 has been released today and this feature is accessible in that release

**Comment by aaschmid** [comment]
Hi @christophd, I really like the feature even if it will not help that much for the above required extendability. As I have already mentioned, I will gather more experience and come back to you if I will have a more concreate idea. 
You can close that ticket if you do not want to implement the ```RetrieveVariableAction``` yourself (or I can create a pull request for it if you want). I know that this feature is just useful using the test runner implementation, getting same variables out of the test context and being able to assert them using normal AssertJ, JUnit, Hamcrest or whatever else assertions ;-)

**Comment by aaschmid** [comment]
But is it possible that ```AssertionException```s of any of the above mentioned libraries are ignore by Citrus. Haven't hat time to look at it in detail but it seems so ;-)
