### ISSUE TITLE
Custom-Function, unclear Exception-Message

### ISSUE THREAD

**Issue by krguse** [christophd/citrus#84]
My custom-function returned in function execute(..) null instead of a string-instance.

Got following exception-message
FAILURE: Caused by: NoSuchFunctionException: Function: ….  could not be found

I think this exception-message is not correct. Maybe an Message like “function <FUNCTION-NAME> did return NULL” would be more helpful.

**Comment by vdsrd** [comment]
Are you sure that, your custom function is really executed. First check your configuration and look in citrus-context.xml if the custom function is configured correctly there, and if yes put a break point in your custom function and check if it is really executed.

Best regards
Tamer

**Comment by krguse** [comment]
Hi Tamer,

thanks for your quick response.

And yes I am sure that everything is correctly configured.

Changing  my return-value from

return null;

to

return “”;

let the exception disappear and everything is running fine.

The exception “NoSuchFunctionException” sounds a little bit like reflection. I assume that the returned value is analyzed and because null is not a valid string-instance (not the correct class) the analyzer is “confused” .

Please try to reproduce it.

Kind Regards
Kai

Von: vdsrd [mailto:notifications@github.com]
Gesendet: Montag, 14. März 2016 3:39
An: christophd/citrus
Cc: Guse, Kai-Rasmus
Betreff: Re: [citrus] Custom-Function, unclear Exception-Message (#84)

Are you sure that, your custom function is really executed. First check your configuration and look in citrus-context.xml if the custom function is configured correctly there, and if yes put a break point in your custom function and check if it is really executed.

Best regards
Tamer

**Comment by vdsrd** [comment]
OK, I could also reproduce the issue. Yes you are right, the exception is misleading.

Kind regards
Tamer

**Comment by krguse** [comment]
Hi Tamer,

Thanks ;-)

Kind Regards
Kai

Von: vdsrd [mailto:notifications@github.com]
Gesendet: Montag, 14. März 2016 3:57
An: christophd/citrus
Cc: Guse, Kai-Rasmus
Betreff: Re: [citrus] Custom-Function, unclear Exception-Message (#84)

OK, I could also reproduce the issue. Yes you are right, the exception is misleading.

Kind regards
Tamer
