### ISSUE TITLE
Content-Length:0 on GET for client.HttpClient with Message to send

### ISSUE THREAD

**Issue by cis-user** [christophd/citrus#91]
I test my server with Rest POST/GET/PUT/DELETE method.
For every request I provide a payload. 

For PUT it works very well.
The code looks like this:

    public void putUser() {
        variable("uid", 12345);
        variable("name", "Luigi");
        echo("uid is: ${uid}");
        echo("name is: ${name}");

        http().client(basicRestfulClient)
              .put("/v1/user/")
              .contentType("application/json")
              .payload("{\"uid\":${uid}, \"name\":\"${name}\"}");

        http().client(basicRestfulClient)
              .response(HttpStatus.OK)
              .messageType(MessageType.JSON)
              .payload("{ \"URI\": \"/v1/user/\", \"action\": \"modifyUser\", \"method\": \"PUT\", \"name\": \"${name}\", \"uid\": ${uid} }");
    }

For GET I have the following:
    public void getUser() {
        variable("uid", 12345);
        echo("uid is: ${uid}");

        http().client(basicRestfulClient)
              .get("/v1/user/")
              .contentType("application/json")
              .payload("{\"uid\":${uid}}");

        http().client(basicRestfulClient)
              .response(HttpStatus.OK)
              .messageType(MessageType.JSON)
              .payload("{ \"URI\": \"/v1/user/\", \"action\": \"getUser\", \"method\": \"GET\", \"uid\": ${uid} }");
    }

When I run GET test I'm getting the error from the server, since my server is expecting the body, and for some reason the body is stripped 

The debug for GET looks like the following :

07:11:07,365 DEBUG    client.HttpClient| Sending HTTP message to: 'http://localhost:8080/v1/user/'
07:11:07,365 DEBUG    client.HttpClient| Message to send:
{"uid":12345}
07:11:07,366 DEBUG ingClientInterceptor| Sending Http request message
07:11:07,369 DEBUG   Logger.Message_OUT| GET http://localhost:8080/v1/user/
Accept:text/plain, application/json, application/*+json, */*
Content-Type:application/json
Content-Length:0

Is it a bug or apache.httpclient doesn't allow any body on GET requests?
Thanks in advance fore your help

**Comment by christophd** [comment]
The body content is automatically removed for GET requests. I think this is particular because Spring framework's RestTemplate or underlying HttpClient is removing the body for GET requests

**Comment by cis-user** [comment]
Thanks a lot for the super quick response. That's what I thought. By the way, you have a nice test framework.
