### ISSUE TITLE
Links to blogs on front page is 404

### ISSUE THREAD

**Issue by davsclaus** [christophd/citrus#93]
On the front page at
http://www.citrusframework.org/

On the bottom right hand side there is a blog section. But those links are broken and return a 404.

I did find the blog entries from a "blog" link in the middle.
https://labs.consol.de/tags/citrus/

It seems maybe the blog links are now using a date in the date in the url such as
https://labs.consol.de/citrus/2014/11/21/testing-apache-camel-part-1.html

But the links on the front page are without that date.

**Comment by christophd** [comment]
The RSS feed was broken due to a jquery library that has been discontinued. Thanks for pointing to this! I personally haven't noticed that for a long time
