### ISSUE TITLE
Support Configurable Paths for Reporters

### ISSUE THREAD

**Issue by kisaakyan** [christophd/citrus#97]
HtmlReporter should provide a way to set the output directory instead of using a hardcoded value

``
    /** Output directory */
    private static final String OUTPUT_DIRECTORY = "test-output" + File.separator + "citrus-reports";
``

**Comment by christophd** [comment]
Fixed! You can customize the reporter using properties:

    citrus.html.report.enabled: Enables/disables HTML report generation (default=true).
    citrus.html.report.directory: Output directory path (default=${project.build.directory}/test-output/citrus-reports).
    citrus.html.report.file: File name for the report file (default=citrus-test-results.html).
    citrus.html.report.template: Template HTML file with placeholders for report results.
    citrus.html.report.detail.template: Template file for detailed test results.
    citrus.html.report.logo: File resource path pointing to a image that is added to top of HTML report.
